### ISSUE TITLE
Signing for Release APK

### ISSUE THREAD

**Issue by vipulasri** [OfficeDev/skype-android-app-sdk-samples#4]
Is there any Proguard Rules for the release apk? or any other configuration to be made for release apk.

**Comment by richardtaylorrt** [comment]
Hi - I'm not quite sure what you are asking.   Are you hitting a specific problem?

- There are no Proguard rules needed to run these sample applications.

- I don't believe you need to add any Proguard rules in order to create an application using this preview SDK.

Let me know if I have misunderstood what you are asking.

**Comment by vipulasri** [comment]
@richardtaylorrt I was getting warnings while applying proguard, which i handled by applying some of the rules in proguard.

```
-keep class com.microsoft.** { *; }
-dontwarn com.microsoft.**

-keep class com.google.common.** { *; }
-dontwarn com.google.common.**

-keep class org.bouncycastle.** { *; }
-dontwarn org.bouncycastle.**
```
